services:
  db:
    env_file:
      - .env
    image: postgres:13
    ports:
      - "5432:5432"
  web:
    env_file:
      - .env
    build: .
    command: ./bin/dev
    volumes:
      - .:/askmybook
    ports:
      - "3333:3000"
    depends_on:
      - db
