services:
  db:
    image: postgres:13
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - .env.production
    command: ./bin/prod
    volumes:
      - .:/askmybook
    ports:
      - "3333:3000"
    depends_on:
      - db
