default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres-nic
  password: o23unrc2opi2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: askymybook

test:
  <<: *default
